ROOT=..
include $(ROOT)/Make.mk

PROGS = filetype access umask chmod unlink rd_symlink getcwd dev_t

all:	$(PROGS)

%:	%.c $(LIBAPUE)
	$(CC) $(CFLAGS) $@.c -o $@ $(LDFLAGS) $(LDLIBS)

clean:
	rm -f $(PROGS) $(TEMPFILES) *.o

include $(ROOT)/Make.libapue.inc
